name: sbti_getting_started
channels:
  - conda-forge
  - defaults
dependencies:
  - git>=2.0.0
  - pip>=20.0.0
  - numpy>=1.21.0,<3.0.0
  - python>=3.9,<3.13
  - jupyter>=1.0.0
  - pip:
    - sbti-finance-tool
