# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: OSS Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install ossaudit
    - name: Run OSS Audit
      id: run_oss_audit
      run: |
        echo ::set-output name=audit::$(ossaudit -f requirements.txt)
    - name: Check vulnerabilities
      if: ${{!startsWith(steps.run_oss_audit.outputs.audit, 'Found 0 vulnerabilities')}}
      run: |
        echo ${{steps.run_oss_audit.outputs.audit}}
        echo "::warning::Vulnerabilities found in the dependencies"
        exit 1

        
